# Generated by Django 5.0.2 on 2024-06-07 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='Company Logo')),
                ('Head_Office', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('Intro_Video', models.FileField(blank=True, max_length=2000, upload_to='videos')),
            ],
            options={
                'verbose_name_plural': 'Company Detail',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Full_Name', models.CharField(max_length=200)),
                ('Billing_Address', models.CharField(max_length=1000)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Whats_App_Number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Phone_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('Business_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Acccount_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Opening_Balance', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('Credit_Limit', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customeer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('Total_Purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_Sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Pending_Payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Recived_Payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_Expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('Purchase_Type', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Supplier_Name', models.CharField(max_length=200)),
                ('Place_Of_Supply', models.CharField(max_length=200)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('UoM', models.CharField(max_length=300)),
                ('Purchase_Screenshot', models.ImageField(upload_to='Purchase Screeshots')),
                ('Quentity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Purchase_Price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
