# Generated by Django 5.0.2 on 2024-06-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_companydetail_phone_dailyproduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufeaturing',
            name='Complete_Production',
            field=models.BooleanField(default=False),
        ),
    ]
