# Generated by Django 5.0.2 on 2024-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_manufeaturing_complete_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufeaturing',
            name='Out_Of_Stock',
            field=models.BooleanField(default=False),
        ),
    ]
