# Generated by Django 5.0.2 on 2024-06-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_manufeaturing_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufeaturing',
            name='Payment_Proof',
            field=models.ImageField(blank=True, null=True, upload_to='Payment Proof/'),
        ),
    ]
