# Generated by Django 5.0.2 on 2024-06-23 05:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_manufeaturing_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturing_Product_Name', models.CharField(max_length=200)),
                ('Supplier_Name', models.CharField(max_length=200)),
                ('Place_Of_Supply', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
                ('Payment_Proof', models.ImageField(blank=True, null=True, upload_to='Payment Proof/')),
                ('Total_Production_Items', models.IntegerField(default=0)),
                ('Total_Purchase_Price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Manufacturing_Expense', models.IntegerField(default=0)),
                ('Total_Sale_Amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('Profit', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('Lose', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('Complete_Production', models.BooleanField(default=False)),
                ('Out_Of_Stock', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Manufeaturing',
        ),
    ]
