# Generated by Django 5.0.2 on 2024-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_manufacturing_delete_manufeaturing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='Total_Sale_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
