# Generated by Django 5.0.2 on 2024-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_manufacturing_total_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='Lose',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='Profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='Total_Purchase_Price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
