# Generated by Django 5.0.2 on 2024-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_manufacturing_lose_alter_manufacturing_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Unit',
            field=models.CharField(choices=[('KG', 'KG'), ('MUN', ' MUN'), ('QUANTITY', 'QUANTITY'), ('OTHERS', 'OTHERS')], default='MUN', max_length=20),
        ),
    ]
