# Generated by Django 5.0.2 on 2024-06-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_manufacturing_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturing',
            old_name='Lose',
            new_name='Profit_OR_Lose',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='Profit',
        ),
    ]
