# Generated by Django 5.0.2 on 2024-06-26 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_rename_lose_manufacturing_profit_or_lose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='Weight',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=100),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Production_Name', models.CharField(max_length=500)),
                ('Items_Or_Balles', models.IntegerField(default=0)),
                ('Weight', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('Weight_Unit', models.CharField(choices=[('KG', 'KG'), ('MUN', ' MUN'), ('QUANTITY', 'QUANTITY'), ('OTHERS', 'OTHERS')], default='MUN', max_length=20)),
                ('Sale_Price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Client_Name', models.CharField(max_length=200)),
                ('Client_Phone_Number', models.CharField(max_length=20)),
                ('Shiping_Address', models.CharField(max_length=1000)),
                ('Shipping_City', models.CharField(max_length=1000)),
                ('Shiping_State', models.CharField(max_length=1000)),
                ('Driver_Name', models.CharField(max_length=200)),
                ('Vehicle_Number', models.CharField(max_length=50)),
                ('Vehicle_Weight', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('Computer_Weight_Slip', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('Driver_Contact', models.CharField(max_length=200)),
                ('Payment_Status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
