# Generated by Django 5.0.2 on 2024-06-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_sale_client_alter_sale_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Client',
        ),
        migrations.AddField(
            model_name='sale',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_ID', to='business.client'),
        ),
    ]
