# Generated by Django 5.0.2 on 2024-06-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_remove_sale_client_sale_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='VECHCLE_WEIGHT_Unit',
            field=models.CharField(choices=[('KG', 'KG'), ('MUN', ' MUN'), ('QUANTITY', 'QUANTITY'), ('OTHERS', 'OTHERS')], default='MUN', max_length=20),
        ),
    ]
