# Generated by Django 5.0.2 on 2024-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_sale_vechcle_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Computer_Weight_Slip',
            field=models.ImageField(upload_to='Sale Splip'),
        ),
    ]
