# Generated by Django 5.0.2 on 2024-06-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_sale_computer_weight_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile'),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile'),
        ),
        migrations.AddField(
            model_name='sale',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile'),
        ),
    ]
