# Generated by Django 5.0.2 on 2024-06-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_client_profile_dailyproduction_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='dailyproduction',
            old_name='profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='manufacturing',
            old_name='profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='profile',
            new_name='userprofile',
        ),
    ]
