# Generated by Django 5.0.2 on 2024-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_rename_profile_client_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
