# Generated by Django 5.0.2 on 2024-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Final_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
