# Generated by Django 5.0.2 on 2024-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_sale_final_amount_alter_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profilepic',
            field=models.ImageField(blank=True, default='media/Company Logo/logo1.png', null=True, upload_to='clientpic/'),
        ),
    ]
