# Generated by Django 5.0.2 on 2024-07-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Paid_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
