# Generated by Django 5.0.2 on 2024-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_sale_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Remaing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
