# Generated by Django 5.0.2 on 2024-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_sale_remaing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Remaing',
            new_name='Remaining',
        ),
    ]
