# Generated by Django 5.0.2 on 2024-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_rename_remaing_sale_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Payment_Slip',
            field=models.ImageField(blank=True, null=True, upload_to='Payment Slip'),
        ),
    ]
