# Generated by Django 5.0.2 on 2024-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_sale_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='GST',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
