# Generated by Django 5.0.2 on 2024-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_sale_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='GST',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
    ]
