# Generated by Django 5.0.2 on 2024-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_manufacturing_manufacture_balles'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Manufacture_Weight',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=100),
        ),
    ]
