# Generated by Django 5.0.2 on 2024-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_expense_userprofile_profile_profit_or_lose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
