# Generated by Django 5.0.2 on 2024-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturing',
            name='id',
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='Manufacturing_Product_Name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
