# Generated by Django 5.0.2 on 2024-07-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_remove_profile_pending_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='media/logo1.png', null=True, upload_to='profilepic/'),
        ),
    ]
