# Generated by Django 5.0.2 on 2024-07-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_profile_email_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
