# Generated by Django 5.0.2 on 2024-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='Total_Purchase_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='media/img/logo1.png', null=True, upload_to='profilepic/'),
        ),
    ]
