# Generated by Django 5.0.2 on 2024-07-12 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_alter_manufacturing_total_purchase_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=500)),
                ('Sale_Production_Name', models.CharField(max_length=500)),
                ('Items_Or_Balles', models.IntegerField(default=0)),
                ('Weight', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('Return_To_Customer_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Payment_Proof', models.ImageField(upload_to='Return Payment Proof')),
                ('Reason_Of_Return', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Client_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='business.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Return', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile')),
            ],
        ),
    ]
