# Generated by Django 5.0.2 on 2024-07-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_sale_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_return',
            name='date',
        ),
    ]
