# Generated by Django 5.0.2 on 2024-07-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_remove_sale_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Acccount_Type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Credit_Limit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Opening_Balance',
        ),
    ]
