# Generated by Django 5.0.2 on 2024-07-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_remove_client_acccount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Acccount_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Credit_Limit',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Opening_Balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
