# Generated by Django 5.0.2 on 2024-07-12 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_client_acccount_type_client_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_return',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
