# Generated by Django 5.0.2 on 2024-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_sale_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Production_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Dumping_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Harvesting_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Labour_Expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Loading_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Machine_Depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Mud_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Packing_Material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Polythene_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Pressing_Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Weight_Losses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Harvesting', 'Harvesting'), ('Pressing', 'Pressing'), ('Dumping', 'Dumping'), ('Polythene', 'Polythene'), ('Mud Cost', 'Mud Cost'), ('Weight Losses', 'Weight Losses'), ('Packing Material', 'Packing Material'), ('Machine Depreciation', 'Machine Depreciation'), ('Loading', 'Loading'), ('Labour', 'Labour'), ('Office Supplies', 'Office Supplies'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
