# Generated by Django 5.0.2 on 2024-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_expense_production_name_manufacturing_dumping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Other_Expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
