# Generated by Django 5.0.2 on 2024-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_manufacturing_other_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Payment_Method',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('CASH', ' CASH '), ('OTHERS', 'OTHERS')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Computer_Weight_Slip',
            field=models.ImageField(blank=True, null=True, upload_to='Sale Splip'),
        ),
    ]
