# Generated by Django 5.0.2 on 2024-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_sale_payment_method_alter_sale_computer_weight_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Manufacturing_Purchase_Typye',
            field=models.CharField(choices=[(' PER ACER', ' PER ACER'), (' PURCHASE WEIGHT', '  PURCHASE WEIGHT'), ('OTHERS', 'OTHERS')], default=' PER ACER', max_length=20),
        ),
    ]
