# Generated by Django 5.0.2 on 2024-08-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0050_remove_manufacturing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Harvest_Type',
            field=models.CharField(choices=[(' WITH_FUEL', ' WITH_FUEL'), ('  WITHOUT_FUEL', '   WITHOUT_FUEL'), ('OTHERS', 'OTHERS')], default=' PER_ACER', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='Manufacturing_Purchase_Type',
            field=models.CharField(choices=[(' PER_ACER', ' PER_ACER'), (' PURCHASE_WEIGHT', '  PURCHASE_WEIGHT'), ('OTHERS', 'OTHERS')], default=' PER_ACER', max_length=20),
        ),
    ]
