# Generated by Django 5.0.2 on 2024-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0052_manufacturing_fuel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Payment_Status',
            field=models.CharField(choices=[('Harvesting', 'Harvesting'), ('Pressing', 'Pressing'), ('Dumping', 'Dumping'), ('Polythene', 'Polythene'), ('Mud Cost', 'Mud Cost'), ('Weight Losses', 'Weight Losses'), ('Packing Material', 'Packing Material'), ('Machine Depreciation', 'Machine Depreciation'), ('Loading', 'Loading'), ('Labour', 'Labour'), ('Office Supplies', 'Office Supplies'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='PAID', max_length=50),
        ),
    ]
