# Generated by Django 5.0.2 on 2024-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0054_expense_paid_amount_expense_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Paid_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Payment_Status',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('PAID', 'PAID')], default='PAID', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Remaining_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
