# Generated by Django 5.0.2 on 2024-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0056_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Harvesting', 'Harvesting'), ('Pressing', 'Pressing'), ('Dumping', 'Dumping'), ('Polythene', 'Polythene'), ('Mud Cost', 'Mud Cost'), ('Weight Losses', 'Weight Losses'), ('Balling Paper', 'Balling Paper'), ('Stitch Paper', ' Stitch Paper'), ('Machine Depreciation', 'Machine Depreciation'), ('Loading', 'Loading'), ('Labour', 'Labour'), ('Office Supplies', 'Office Supplies'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
