# Generated by Django 5.0.2 on 2024-08-09 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0058_alter_expense_bill_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loading_Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Leader', models.CharField(max_length=500)),
                ('Credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Bales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoadingLabour', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingLabourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Leader', models.CharField(max_length=500)),
                ('Bankar', models.CharField(max_length=500)),
                ('Credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Bales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Per_Bale_Price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Remaining', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Payment_Status', models.CharField(choices=[('CREDIT', 'CREDIT'), ('PAID', 'PAID')], default='PAID', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoadingRecord', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProducctionLabourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Leader', models.CharField(max_length=500)),
                ('Bankar', models.CharField(max_length=500)),
                ('Credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Bales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Per_Bale_Price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Remaining', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Payment_Status', models.CharField(choices=[('CREDIT', 'CREDIT'), ('PAID', 'PAID')], default='PAID', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionRecord', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Leader', models.CharField(max_length=500)),
                ('Credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Bales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionLabour', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.profile')),
            ],
        ),
    ]
