# Generated by Django 5.0.2 on 2024-08-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0059_loading_labour_loadinglabourrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='Production_and_Expense_Proof_Screenshot',
        ),
    ]
