# Generated by Django 5.0.2 on 2024-08-10 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0060_remove_dailyproduction_production_and_expense_proof_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadinglabourrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producctionlabourrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
