# Generated by Django 5.0.2 on 2024-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0061_loadinglabourrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
