# Generated by Django 5.0.2 on 2024-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0062_alter_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producctionlabourrecord',
            name='Paid',
        ),
    ]
