# Generated by Django 5.0.2 on 2024-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0063_remove_producctionlabourrecord_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Estimated_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Per_Kg_Or_Mund_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Purchase_Price_After_Weight_Lose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Weight_After_Weight_Lose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
