# Generated by Django 5.1.1 on 2024-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_manufacturing_estimated_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Weight_Lose_Value',
            field=models.IntegerField(default=0),
        ),
    ]
