# Generated by Django 5.1.1 on 2024-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_manufacturing_weight_lose_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='Paid_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Payment_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='Remaining_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
