# Generated by Django 5.1.1 on 2024-10-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0066_manufacturing_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading_labour',
            name='Labour_Id',
            field=models.IntegerField(default=0),
        ),
    ]
