# Generated by Django 5.1.1 on 2024-10-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_loading_labour_labour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loading_labour',
            name='Labour_Id',
        ),
        migrations.AddField(
            model_name='loadinglabourrecord',
            name='Labour_Id',
            field=models.IntegerField(default=0),
        ),
    ]
