# Generated by Django 5.1.1 on 2024-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0069_producctionlabourrecord_labour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading_labour',
            name='Advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='production_labour',
            name='Advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
