# Generated by Django 5.1.1 on 2024-10-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0071_loading_labour_advance_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loading_labour_advance_payment',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='production_labour_advance_payment',
            name='userprofile',
        ),
    ]
